version: '3.8'

networks:
  qv-network:
    driver: bridge

volumes:
  postgres_data:

services:
  # --- ИНФРАСТРУКТУРА ---

  postgres:
    image: postgres:15-alpine
    container_name: qv-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: qv_main
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - qv-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: qv-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - qv-network

  zipkin:
    image: openzipkin/zipkin
    container_name: qv-zipkin
    ports:
      - "9411:9411"
    networks:
      - qv-network

  # --- JAVA СЕРВИСЫ ---

  discovery:
    build: ./qv-discovery
    container_name: qv-discovery
    ports:
      - "8761:8761"
    networks:
      - qv-network

  gateway:
    build: ./qv-gateway
    container_name: qv-gateway
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/
    depends_on:
      - discovery
    networks:
      - qv-network

  voting-service:
    build: ./qv-voting
    container_name: qv-voting
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/voting_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_RABBITMQ_HOST: rabbitmq
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/
    depends_on:
      - postgres
      - rabbitmq
      - discovery
    networks:
      - qv-network

  wallet-service:
    build: ./qv-wallet
    container_name: qv-wallet
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/wallet_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_RABBITMQ_HOST: rabbitmq
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka/
    depends_on:
      - postgres
      - rabbitmq
      - discovery
    networks:
      - qv-network