server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: voting-route
          uri: lb://VOTING-SERVICE
          predicates:
            - Path=/api/votes/**
        - id: history-route
          uri: lb://HISTORY-SERVICE
          predicates:
            - Path=/api/history/**
          filters:
            - RewritePath=/api/history/(?<segment>.*), /history/$\{segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans